name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    defaults:
      run:
        shell: ${{ matrix.shell }}
    strategy:
      matrix:
        os: [windows-2022, windows-2019, ubuntu-latest]
        shell: [pwsh, bash]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set env
        run: |
          echo "VERSION=5" >> $GITHUB_ENV
      - name: get env
        run: |
          echo "${{ env.VERSION }}"
        env:
          VERSION: ${{ env.VERSION }}
